version: "3"
services:
  redis:
    build: 
      context: .
    image: 
      ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name:
        redis
    ports:
      - 6379:6379
    command:
      ["redis-server",  "c:\\conf\\redis.conf"]
    volumes:
      - ${CONFIG_DIR}:c:\conf:ro
      - ${DATA_DIR}:c:\data:rw

#
# EOF (2024/06/18)
#